apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-nfs-server" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ printf "%s-nfs-server" .Release.Name }}
  template:
    metadata:
      labels:
        role: {{ printf "%s-nfs-server" .Release.Name }}
    spec:
      containers:
      - name: {{ printf "%s-nfs-server" .Release.Name }}
        image: {{.Values.image}}
        ports:
          - name: nfs
            containerPort: {{.Values.ports.nfs }}
          - name: mountd
            containerPort: {{.Values.ports.mountd }}
          - name: rpcbind
            containerPort: {{.Values.ports.rpcbind }}
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: disk
      volumes:
        - name: disk
          gcePersistentDisk:
            pdName: {{.Values.diskName}}
            fsType: ext4