apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvStorage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ printf "%s-nfs-server.%s.%s" .Release.Name  .Release.Namespace .Values.cluster }}
    path: "/"
 