apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-nfs-server" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: nfs
      port: {{.Values.ports.nfs }}
    - name: mountd
      port: {{.Values.ports.mountd }}
    - name: rpcbind
      port: {{.Values.ports.rpcbind }}
  selector:
    role: {{ printf "%s-nfs-server" .Release.Name }}